//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public int id { get; set; }
        public Nullable<int> Event_id { get; set; }
        public string email { get; set; }
    
        public virtual EventDetail EventDetail { get; set; }
    }
}
